-- PI EduTrack V12: Supabase database + RLS + Realtime + Storage
-- Run this entire file in Supabase SQL Editor.

create extension if not exists pgcrypto;

do $$ begin
  create type public.user_gender as enum ('BOYS','GIRLS');
exception when duplicate_object then null; end $$;
do $$ begin
  create type public.user_role as enum ('STUDENT','ADMIN');
exception when duplicate_object then null; end $$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  mobile text not null unique,
  gender public.user_gender not null,
  age integer not null check (age between 10 and 100),
  school text not null,
  klass text not null,
  department text not null,
  district text not null,
  photo_url text,
  group_id public.user_gender generated always as (gender) stored,
  role public.user_role not null default 'STUDENT',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  group_id public.user_gender not null,
  author_id uuid not null references public.profiles(id) on delete cascade,
  text text not null default '',
  message_type text not null default 'TEXT',
  attachment jsonb,
  payload jsonb,
  reply_to bigint references public.messages(id) on delete set null,
  pinned boolean not null default false,
  edited_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists messages_group_created_idx on public.messages(group_id,created_at);

create table if not exists public.message_reactions (
  message_id bigint references public.messages(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete cascade,
  emoji text not null,
  created_at timestamptz not null default now(),
  primary key(message_id,user_id)
);

create table if not exists public.message_reads (
  message_id bigint references public.messages(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete cascade,
  read_at timestamptz not null default now(),
  primary key(message_id,user_id)
);

create table if not exists public.poll_votes (
  message_id bigint references public.messages(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete cascade,
  option_index integer not null,
  created_at timestamptz not null default now(),
  primary key(message_id,user_id)
);

create table if not exists public.announcements (
  id bigint generated by default as identity primary key,
  group_id public.user_gender not null,
  author_id uuid not null references public.profiles(id) on delete cascade,
  text text not null,
  attachment jsonb,
  pinned boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  message_id bigint references public.messages(id) on delete cascade,
  reporter_id uuid references public.profiles(id) on delete cascade,
  reason text not null,
  status text not null default 'PENDING',
  created_at timestamptz not null default now()
);

create table if not exists public.blocks (
  blocker_id uuid references public.profiles(id) on delete cascade,
  blocked_id uuid references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(blocker_id,blocked_id)
);

create or replace function public.is_group_member(g public.user_gender)
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.profiles p where p.id=auth.uid() and p.gender=g);
$$;
create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='ADMIN');
$$;

alter table public.profiles enable row level security;
alter table public.messages enable row level security;
alter table public.message_reactions enable row level security;
alter table public.message_reads enable row level security;
alter table public.poll_votes enable row level security;
alter table public.announcements enable row level security;
alter table public.reports enable row level security;
alter table public.blocks enable row level security;

drop policy if exists profiles_select_group on public.profiles;
create policy profiles_select_group on public.profiles for select to authenticated using (public.is_group_member(gender) or id=auth.uid());
drop policy if exists profiles_insert_self on public.profiles;
create policy profiles_insert_self on public.profiles for insert to authenticated with check (id=auth.uid() and role='STUDENT');
drop policy if exists profiles_update_self on public.profiles;
create policy profiles_update_self on public.profiles for update to authenticated using (id=auth.uid() or public.is_admin()) with check (id=auth.uid() or public.is_admin());

drop policy if exists messages_select_group on public.messages;
create policy messages_select_group on public.messages for select to authenticated using (public.is_group_member(group_id));
drop policy if exists messages_insert_group on public.messages;
create policy messages_insert_group on public.messages for insert to authenticated with check (author_id=auth.uid() and public.is_group_member(group_id));
drop policy if exists messages_update_own_or_admin on public.messages;
create policy messages_update_own_or_admin on public.messages for update to authenticated using (author_id=auth.uid() or public.is_admin()) with check (author_id=auth.uid() or public.is_admin());
drop policy if exists messages_delete_own_or_admin on public.messages;
create policy messages_delete_own_or_admin on public.messages for delete to authenticated using (author_id=auth.uid() or public.is_admin());

create policy reactions_group_select on public.message_reactions for select to authenticated using (exists(select 1 from public.messages m where m.id=message_id and public.is_group_member(m.group_id)));
create policy reactions_self_write on public.message_reactions for all to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());
create policy reads_group_select on public.message_reads for select to authenticated using (user_id=auth.uid() or exists(select 1 from public.messages m where m.id=message_id and m.author_id=auth.uid()));
create policy reads_self_write on public.message_reads for all to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());
create policy poll_group_select on public.poll_votes for select to authenticated using (exists(select 1 from public.messages m where m.id=message_id and public.is_group_member(m.group_id)));
create policy poll_self_write on public.poll_votes for all to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());

create policy announcements_group_select on public.announcements for select to authenticated using (public.is_group_member(group_id));
create policy announcements_admin_write on public.announcements for all to authenticated using (public.is_admin()) with check (public.is_admin() and author_id=auth.uid());
create policy reports_self_insert on public.reports for insert to authenticated with check (reporter_id=auth.uid());
create policy reports_self_or_admin_select on public.reports for select to authenticated using (reporter_id=auth.uid() or public.is_admin());
create policy reports_admin_update on public.reports for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy blocks_self on public.blocks for all to authenticated using (blocker_id=auth.uid()) with check (blocker_id=auth.uid());

-- Storage bucket. Public read is intentionally NOT required for messages if you later switch to signed URLs.
insert into storage.buckets (id,name,public) values ('community-media','community-media',true) on conflict (id) do nothing;
drop policy if exists community_media_upload on storage.objects;
create policy community_media_upload on storage.objects for insert to authenticated with check (bucket_id='community-media' and (storage.foldername(name))[1] in ('profiles','messages') and (storage.foldername(name))[2]=auth.uid()::text);
drop policy if exists community_media_read on storage.objects;
create policy community_media_read on storage.objects for select to authenticated using (bucket_id='community-media');
drop policy if exists community_media_delete on storage.objects;
create policy community_media_delete on storage.objects for delete to authenticated using (bucket_id='community-media' and (storage.foldername(name))[2]=auth.uid()::text);

-- Realtime: add only tables that the PWA subscribes to.
alter publication supabase_realtime add table public.messages;
alter publication supabase_realtime add table public.profiles;
alter publication supabase_realtime add table public.announcements;

-- IMPORTANT: after creating your owner profile, promote it server-side in SQL:
-- update public.profiles set role='ADMIN' where mobile='+8801XXXXXXXXX';
